### ISSUE TITLE
Tests failing on Python 2.7 because of unicode

### ISSUE THREAD

**Issue by jarondl** [jarondl/pygtfs#21]
Hi @elad661,
The changes you have made in #17 break Python 2 support. Can you have a look at the build errors https://travis-ci.org/jarondl/pygtfs/jobs/118716436 ?

If you don't have time to debug this, I'll try to solve it when I have time.

Yaron

**Comment by elad661** [comment]
I don't have time to debug this this week, but the error seems obvious enough from a quick look... a lack of `u` in the Hebrew string in line 50 of test.py

It'd probably be better to add `from __future__ import unicode_literals` to this file and remove all the `u`s, in the fie, but adding a `u` is also a valid solution.

Also, since the file now has unicode strings in it, it'd also need a `#coding: utf8` line as the first line for "proper" python2 support.

**Comment by jarondl** [comment]
Thank you @elad661,
closed.
