### ISSUE TITLE
GTFS format extensions

### ISSUE THREAD

**Issue by Zebble** [jarondl/pygtfs#27]
Some GTFS providers seem to have started using extensions to the format. For example, Toronto's GO Transit adds one more value to the list of valid location_type's.

Extensions list is here:

https://support.google.com/transitpartners/answer/2450962?hl=en

Fix for this specific issue is:

gtfs_entities.py: line 166, change list from [None,0,1] to [None,0,1,2]

I added some additional info to the _validate_int_choice function as well, to assist with debugging:

line 60:

assert int_value in int_choice, "%s value outside limits: %r not in %s" % (key,int_value,int_choice[0:100])

**Comment by jarondl** [comment]
Hi @Zebble,
I think we can safely incorporate the extensions appearing on that page to pygtfs, because they are semi-official.
Also your proposal in line 60 seems like a good idea, because we do get many bug reports about these validations.

Do you want to submit a pull-request? Or should I code these changes?

Thank you,
Yaron

**Comment by Zebble** [comment]
Thanks Yaron!
Feel free to code the changes.
